# generated by fastapi-codegen:
#   filename:  openapi.json
#   timestamp: 2024-10-22T11:04:04+00:00

from __future__ import annotations

from fastapi import APIRouter

from ..dependencies import *

router = APIRouter(tags=['courier'])


@router.get(
    '/admin/courier/messages',
    response_model=List[Message],
    responses={'400': {'model': ErrorGeneric}, 'default': {'model': ErrorGeneric}},
    tags=['courier'],
)
def list_courier_messages(
    page_size: Optional[conint(ge=1, le=1000)] = 250,
    page_token: Optional[str] = None,
    status: Optional[CourierMessageStatus] = None,
    recipient: Optional[str] = None,
) -> Union[List[Message], ErrorGeneric]:
    """
    List Messages
    """
    pass


@router.get(
    '/admin/courier/messages/{id}',
    response_model=Message,
    responses={'400': {'model': ErrorGeneric}, 'default': {'model': ErrorGeneric}},
    tags=['courier'],
)
def get_courier_message(id: str) -> Union[Message, ErrorGeneric]:
    """
    Get a Message
    """
    pass
