# generated by fastapi-codegen:
#   filename:  openapi.json
#   timestamp: 2024-10-22T11:04:04+00:00

from __future__ import annotations

from fastapi import APIRouter

from ..dependencies import *

router = APIRouter(tags=['jwk'])


@router.delete(
    '/admin/keys/{set}',
    response_model=None,
    responses={'default': {'model': ErrorOAuth2}},
    tags=['jwk'],
)
def delete_json_web_key_set(set: str) -> Optional[ErrorOAuth2]:
    """
    Delete JSON Web Key Set
    """
    pass


@router.get(
    '/admin/keys/{set}',
    response_model=JsonWebKeySet,
    responses={'default': {'model': ErrorOAuth2}},
    tags=['jwk'],
)
def get_json_web_key_set(set: str) -> Union[JsonWebKeySet, ErrorOAuth2]:
    """
    Retrieve a JSON Web Key Set
    """
    pass


@router.post(
    '/admin/keys/{set}',
    response_model=None,
    responses={'201': {'model': JsonWebKeySet}, 'default': {'model': ErrorOAuth2}},
    tags=['jwk'],
)
def create_json_web_key_set(
    set: str, body: CreateJsonWebKeySet = ...
) -> Optional[Union[JsonWebKeySet, ErrorOAuth2]]:
    """
    Create JSON Web Key
    """
    pass


@router.put(
    '/admin/keys/{set}',
    response_model=JsonWebKeySet,
    responses={'default': {'model': ErrorOAuth2}},
    tags=['jwk'],
)
def set_json_web_key_set(
    set: str, body: JsonWebKeySet = None
) -> Union[JsonWebKeySet, ErrorOAuth2]:
    """
    Update a JSON Web Key Set
    """
    pass


@router.delete(
    '/admin/keys/{set}/{kid}',
    response_model=None,
    responses={'default': {'model': ErrorOAuth2}},
    tags=['jwk'],
)
def delete_json_web_key(set: str, kid: str = ...) -> Optional[ErrorOAuth2]:
    """
    Delete JSON Web Key
    """
    pass


@router.get(
    '/admin/keys/{set}/{kid}',
    response_model=JsonWebKeySet,
    responses={'default': {'model': ErrorOAuth2}},
    tags=['jwk'],
)
def get_json_web_key(set: str, kid: str = ...) -> Union[JsonWebKeySet, ErrorOAuth2]:
    """
    Get JSON Web Key
    """
    pass


@router.put(
    '/admin/keys/{set}/{kid}',
    response_model=JsonWebKey,
    responses={'default': {'model': ErrorOAuth2}},
    tags=['jwk'],
)
def set_json_web_key(
    set: str, kid: str = ..., body: JsonWebKey = None
) -> Union[JsonWebKey, ErrorOAuth2]:
    """
    Set JSON Web Key
    """
    pass
