# generated by fastapi-codegen:
#   filename:  openapi.json
#   timestamp: 2024-10-22T11:04:04+00:00

from __future__ import annotations

from fastapi import APIRouter

from ..dependencies import *

router = APIRouter(tags=['wellknown'])


@router.get(
    '/.well-known/jwks.json',
    response_model=JsonWebKeySet,
    responses={'default': {'model': ErrorOAuth2}},
    tags=['wellknown'],
)
def discover_json_web_keys() -> Union[JsonWebKeySet, ErrorOAuth2]:
    """
    Discover Well-Known JSON Web Keys
    """
    pass
