# generated by fastapi-codegen:
#   filename:  openapi.json
#   timestamp: 2024-10-22T11:04:04+00:00

from __future__ import annotations

from fastapi import FastAPI

from .routers import (
    courier,
    events,
    frontend,
    identity,
    jwk,
    metadata,
    o_auth2,
    oidc,
    permission,
    project,
    relationship,
    wellknown,
    workspace,
)

app = FastAPI(
    contact={'email': 'support@ory.sh', 'name': 'API Support'},
    description='Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed\nwith a valid Personal Access Token. Public APIs are mostly used in browsers.\n',
    license={
        'name': 'Apache 2.0',
        'url': 'https://www.apache.org/licenses/LICENSE-2.0.html',
    },
    termsOfService='/ptos',
    title='Ory APIs',
    version='latest',
    servers=[
        {
            'url': 'https://{project-slug}.projects.oryapis.com/',
            'variables': {
                'project': {
                    'default': 'playground',
                    'description': 'Your Ory Network Project slug. You can find it in the [Ory Network Console](https://console.ory.sh/projects/current/developers/guides).',
                }
            },
        }
    ],
)

app.include_router(courier.router)
app.include_router(events.router)
app.include_router(frontend.router)
app.include_router(identity.router)
app.include_router(jwk.router)
app.include_router(metadata.router)
app.include_router(o_auth2.router)
app.include_router(oidc.router)
app.include_router(permission.router)
app.include_router(project.router)
app.include_router(relationship.router)
app.include_router(wellknown.router)
app.include_router(workspace.router)


@app.get("/")
async def root():
    return {"message": "Gateway of the App"}
